//
// Created by Anton Romanova on 16/12/2021.
//

#ifndef PROJETCHAT_SRC_COMMON_EXIT_CODES_H_
#define PROJETCHAT_SRC_COMMON_EXIT_CODES_H_

#define NORMAL_EXIT 0
#define EXIT_BAD_USAGE_ERROR 1
#define EXIT_SOCK_ERROR 2
#define EXIT_OTHER_ERROR 3

#endif //PROJETCHAT_SRC_COMMON_EXIT_CODES_H_
